version: 2.1
orbs:
  aws-ecr: circleci/aws-ecr@6.2.0
  aws-ecs: circleci/aws-ecs@0.0.11
workflows:
  build-and-deploy:
    jobs:
      - aws-ecr/build_and_push_image:
        account-url: "${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_REGION}.amazonaws.com"
        repo: "${MY_APP_PREFIX}"
        region: ${AWS_REGION}
        tag: "${CIRCLE_SHA1}"
      - aws-ecs/deploy-service-update:
        requires:
          - aws-ecr/build_and_push_image
        family: "${MY_APP_PREFIX}"
        cluster-name: "${MY_APP_PREFIX}"
        container-image-name-updates: "container=${MY_APP_PREFIX},tag=${CIRCLE_SHA1}"